image:
  repository: tccr.io/truecharts/wireshark
  pullPolicy: IfNotPresent
  tag: 3.6.5@sha256:f0c1029f689fd57fa6cf1d9ddb395cb386e4b33a540e9b11a3e63f013b5acb34

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

hostNetwork: true

service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: HTTP
        port: 3000

probes:
  liveness:
    path: /
  readiness:
    path: /
  startup:
    path: /

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
