image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webtop
  tag: latest@sha256:a194a837e82b40707e1b5ecb96c613d5749f2cd1d9b85591a3e5660a68dd47c2

env:
  KEYBOARD: ""
  CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 33000
        protocol: HTTP

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  enabled: true
