image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/universal-media-server
  tag: latest@sha256:e71230b1e2b6e330de0ca59c3b64c991a1788ca1c67df3e91ae3a8269e1c22ea

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 9001
        protocol: HTTP
        targetPort: 9001
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        port: 1044
        protocol: TCP
        targetPort: 1044
  api:
    enabled: true
    ports:
      api:
        enabled: true
        port: 5001
        protocol: TCP
        targetPort: 5001

persistence:
  config:
    enabled: true
    mountPath: /root/.config/UMS/
  media:
    enabled: true
    mountPath: /media

portal:
  enabled: true
