image:
  repository: tccr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: 1.6.17@sha256:a85c50e76fb9a017e6bceaf074d3b562c72c082e77e2cf69eff90276912d9dc9

service:
  main:
    ports:
      main:
        port: 11211
        targetPort: 11211

portal:
  enabled: false
