image:
  repository: tccr.io/truecharts/monica
  tag: v3.7.0@sha256:3bd0facc2acb66100eed9b42defee775a6fbae6ba788bf793a4ebd2aa6da8cd3
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  APP_ENV: production
  APP_URL: https://crm.k8s-at-home.com
  DB_DATABASE: monica
  DB_USERNAME: monica
  DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  DB_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  APP_KEY:
    secretKeyRef:
      name: appkey
      key: appkey

service:
  main:
    ports:
      main:
        port: 10119
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/var/www/html/storage"

mariadb:
  enabled: true
  mariadbUsername: monica
  mariadbDatabase: monica
  existingSecret: "mariadbcreds"

portal:
  enabled: true
