env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/twonky-server
  tag: latest@sha256:d04aba6668d197a8869ec280cef56b8e352efaf6a345c756655bb51f15bed453
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 9000
        protocol: TCP
        targetPort: 9000

portal:
  enabled: true
