name: "SCALE: catalog-tests"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  catalog-tests:
    name: Test SCALE Catalog
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:v3.1.1@sha256:78ad845f363f3b7bab45610574e01c087d123cfa168fdace09cb94e55fd182c4
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        name: Checkout
        with:
          fetch-depth: 100
          ref: ${{ inputs.checkoutCommit }}

      - name: Setting repo parent dir as safe safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          repository: truecharts/catalog
          path: catalog

      - name: build-and-run
        run: |
          tools/build-release.sh

      - uses: vishnudxb/cancel-workflow@c3c77eb4383ba7d023e6614a07d94fe990501ac6 # tag=v1.2
        if: failure()
        with:
          repo: truecharts/charts
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
