name: "Prune Old Releases"

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "prune old releases"
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0
      - uses: actions/delete-package-versions@a31a43afa6c2d3afdf8b5f1e311b2dc75585932e # tag=v3
        with:
          min-versions-to-keep: 200
